In [1]:
import numpy as np

In [3]:
a=[1,2,3,4]
b=[5,6,7,8]
a+b

[1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
[a[i]+b[i] for i in range (len(a))]

[6, 8, 10, 12]

In [6]:
a=np.array([4,5,6,7])
b=np.array([3,4,6,9])
a+b

array([ 7,  9, 12, 16])

In [7]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])  
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr[:,2:3]  #st row : end row ,st col : end col

array([[3],
       [6],
       [9]])

In [16]:
arr[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [17]:
arr[:,:1]

array([[1],
       [4],
       [7]])

In [18]:
arr[:,1:2]

array([[2],
       [5],
       [8]])

In [19]:
arr[:1,:]

array([[1, 2, 3]])

In [20]:
arr[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [21]:
arr[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [22]:
arr[:,:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr[1:2,:]

array([[4, 5, 6]])

In [33]:
arr[1:,::2]

array([[4, 6],
       [7, 9]])

In [37]:
np.eye(3,3).astype("int32").dtype

dtype('int32')

In [38]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [39]:
np.arange(0,10,3) #vectors

array([0, 3, 6, 9])

In [40]:
a = np.arange(10,100,5) 

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [42]:
a[a>2]

array([4, 5, 6, 7])

In [50]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [ ]:
#vector operation

In [52]:
a=np.array([1,2,3])
a+2

array([3, 4, 5])

In [53]:
a=np.array([1,2,3])
a^3

array([2, 1, 0])

In [54]:
a=np.array([1,2,3])
a*4

array([ 4,  8, 12])

In [55]:
#vector operations with scalar values

In [57]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [59]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [60]:
a=np.array([[9,2],[5,8]])
b=np.array([[3,6],[2,1]])
a,b

(array([[9, 2],
        [5, 8]]),
 array([[3, 6],
        [2, 1]]))

In [61]:
np.dot(a,b)

array([[31, 56],
       [31, 38]])

In [72]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [76]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [77]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

In [78]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [79]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [80]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [81]:
a

array([[1, 2],
       [3, 4]])

In [82]:
a=([1,2,3,4,5,6,7,7,8,9,8,8])
a

[1, 2, 3, 4, 5, 6, 7, 7, 8, 9, 8, 8]

In [83]:
len(a)

12

In [85]:
np.reshape(a,(3,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 7],
       [8, 9, 8, 8]])

In [86]:
np.reshape(a,(6,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 7],
       [8, 9],
       [8, 8]])

In [111]:
a=np.array([1,2,3,4,5,6,7,7,8,9,8,8])
a

array([1, 2, 3, 4, 5, 6, 7, 7, 8, 9, 8, 8])

In [104]:
len(a)

12

In [108]:
np.resize(a,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 7, 8]])

In [113]:
np.split(a,4)


[array([1, 2, 3]), array([4, 5, 6]), array([7, 7, 8]), array([9, 8, 8])]

In [134]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [135]:
b=a.view()

In [136]:
b[0]=10

In [137]:
a,b

(array([10,  2,  3,  4,  5,  6]), array([10,  2,  3,  4,  5,  6]))

In [140]:
c=a.copy()

In [141]:
a,c

(array([10,  2,  3,  4,  5,  6]), array([10,  2,  3,  4,  5,  6]))

In [127]:
c[0]=11

In [142]:
a,c

(array([10,  2,  3,  4,  5,  6]), array([10,  2,  3,  4,  5,  6]))

In [144]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
np.sum(a,axis=0)

array([12, 15, 18])

In [146]:
def mean(array):
    n=len(array)
    return np.sum(array)/n

In [148]:
mean(np.array([1,2,3,4,5,6]))

np.float64(3.5)

In [149]:
def varience(array):
    n = len(array)
    m = mean(array)
    return np.sum((array - m)**2)/n

In [151]:
varience(np.array([1,2,3,4,5,6]))

np.float64(2.9166666666666665)

In [157]:
def std(array):
    v = varience(array)
    return np.sqrt(v)

In [158]:
std(np.array([1,2,3,4,5,6]))

np.float64(1.707825127659933)

In [162]:
import numpy as np
a=np.array([6,7,8,9])
a

array([6, 7, 8, 9])

In [ ]:
#min max scalar vector 
#formula x-xmin /xmax-xmin

In [163]:
np.min(a)

np.int64(6)

In [164]:
np.max(a)


np.int64(9)

In [168]:
result=((a-a.min())/(a.max()-a.min()))
result

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [188]:
#std scalar
#formula z= x-u/varience

In [189]:
import numpy as np
a=np.array([40,50,60,70])
a

array([40, 50, 60, 70])

In [190]:
std_scalar=(a-np.mean(a)/np.std(a))
std_scalar

array([35.08065045, 45.08065045, 55.08065045, 65.08065045])

#sigmoid formula 1/1+e^(-x)

In [200]:
import numpy as np
a=np.array([-4,9])
a

array([-4,  9])

In [201]:
sigmoid=(1/(1+ np.exp(-a)))
sigmoid

array([0.01798621, 0.99987661])

In [193]:
#task_2

In [198]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshaped = arr.reshape(3, 4)
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [199]:
#pandas